version: '3.4'

x-app: &default
    networks:
        - mynetwork

services:
    mongo:
        <<: *default
        image: mongo
        hostname: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=local
            - MONGO_INITDB_ROOT_PASSWORD=lacol
            - MONGO_INITDB_DATABASE=default
        volumes:
            - mongo_data:/data/db

    server:
        <<: *default
        image: registry.gitlab.com/polytechnique-montr-al/log2990/20213/equipe-301/log2990-301/server:latest
        build:
            context: ..
            dockerfile: Dockerfile
            target: final
        environment:
            - DB_HOST=@mongo/default?retryWrites=true&w=majority
            - DB_USER=local
            - DB_PASSWORD=lacol
        hostname: server
        depends_on:
            - mongo
        ports:
            - "3000:3000"

networks:
    mynetwork:

volumes:
    mongo_data:
