version: '3.4'

x-app: &default
    networks:
        - mynetwork

services:
    mongo:
        <<: *default
        image: mongo
        hostname: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=local
            - MONGO_INITDB_ROOT_PASSWORD=lacol
            - MONGO_INITDB_DATABASE=Scrabble
        volumes:
            - mongo_data:/data/db

    server:
        <<: *default
        build:
            context: ..
            dockerfile: server/Dockerfile
            target: final
        image: registry.gitlab.com/polytechnique-montr-al/log2990/20213/equipe-301/log2990-301/server:latest

        environment:
            - DB_URL=mongodb://local:lacol@mongo
        hostname: server
        depends_on:
            - mongo
        ports:
            - "3000:3000"

networks:
    mynetwork:

volumes:
    mongo_data:
